"""Maxwell backend using PyAEDT (Maxwell2d + Maxwell3d)."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

from ..models import DesignModel, NodeModel
from .base import SolveResult, SolverBackend

logger = logging.getLogger(__name__)


class MaxwellBackend(SolverBackend):
    """PyAEDT-based Maxwell solver backend (2D and 3D).

    Delegates all geometry/material/excitation/setup to
    ``moa_actuator.dosa_maxwell.apply_dosa_to_maxwell()``.
    """

    def __init__(
        self,
        aedt_version: str = "2026.1",
        non_graphical: bool = True,
        new_desktop: bool = True,
        solution_type: str = "MagnetostaticZ",
    ):
        self.aedt_version = aedt_version
        self.non_graphical = non_graphical
        self.new_desktop = new_desktop
        self.solution_type = solution_type

    @property
    def name(self) -> str:
        return "maxwell"

    @property
    def supported_modes(self) -> list[str]:
        return ["2d", "3d"]

    def solve(
        self,
        design: DesignModel,
        mode: str = "2d",
        out_dir: str | None = None,
        dry_run: bool = False,
        build_only: bool = False,
        **kwargs: Any,
    ) -> SolveResult:
        out_path = Path(out_dir) if out_dir else Path("./output")
        out_path.mkdir(parents=True, exist_ok=True)

        project_name = design.name or "DoSA_Project"
        project_file = str((out_path / f"{project_name}.aedt").resolve())

        if self.new_desktop:
            i = 1
            while Path(project_file + ".lock").exists():
                project_name = f"{design.name or 'DoSA_Project'}_{i}"
                project_file = str((out_path / f"{project_name}.aedt").resolve())
                i += 1

        if dry_run:
            return SolveResult(
                ok=True, mode=mode, solver="maxwell",
                commands=[], errors=[],
                project_path=None,
            )

        # ── delegate to dosa_maxwell.apply ────────────────────────────────
        try:
            from ..dosa_maxwell import apply_dosa_to_maxwell
            from ..dosa_maxwell.profiles import MaxwellProfile
        except ImportError as exc:
            return SolveResult(
                ok=False, mode=mode, solver="maxwell",
                commands=[], errors=[f"[import] dosa_maxwell not found: {exc}"],
                project_path=None,
            )

        errors: list[str] = []
        app = self._create_session(project_file, project_name, mode, errors)
        if app is None:
            return SolveResult(
                ok=False, mode=mode, solver="maxwell",
                commands=[], errors=errors,
                project_path=None,
            )

        # 1. Check if the project is already built (in running desktop)
        is_built = False
        if not self.new_desktop:
            try:
                # If there are objects in the modeler, the design geometry is already built
                if app.modeler.object_names:
                    is_built = True
            except Exception:
                pass

        result_ok = True
        result_commands = []
        result_errors = []

        # 2. Build the project if not already built
        if not is_built:
            logger.info("Project not built yet. Building...")
            # Build a MaxwellProfile from this backend's settings.
            # solution_type for the profile must be the base type without Z/XY suffix
            # because apply_dosa_to_maxwell reads geometry mode from the live app.
            base_sol = self.solution_type
            for suffix in ("Z", "XY"):
                if base_sol.endswith(suffix):
                    base_sol = base_sol[: -len(suffix)]
                    break

            prof = MaxwellProfile(
                name="moa_backend",
                source_pdf="internal",
                solution_type=base_sol,
                time_step=kwargs.get("time_step", "1ms"),
                stop_time=kwargs.get("stop_time", "10ms"),
                mesh_hint="balanced",
                notes="auto-generated by MaxwellBackend",
            )

            result = apply_dosa_to_maxwell(design, app, profile=prof)
            result_ok = result.ok
            result_commands = result.get("commands", [])
            result_errors = result.get("errors", [])
            
            try:
                app.save_project()
            except Exception:
                pass
        else:
            logger.info("Project already built in running session. Skipping build phase.")

        # 3. Solve if build_only is False and build succeeded
        if not build_only and result_ok:
            logger.info("Solve phase: Triggering Maxwell analysis...")
            try:
                # Attempt direct Optimetrics solve first (which handles Parametric setups robustly)
                solved_via_opti = False
                try:
                    logger.info("Accessing Optimetrics module...")
                    oModule = app.odesign.GetModule("Optimetrics")
                    # Check if there are any setups defined in parametrics (using PyAEDT properties safely)
                    has_opti_setups = False
                    try:
                        has_opti_setups = bool(app.parametrics.setup_names)
                    except Exception:
                        # Fallback: assume setup exists and try to call SolveAllSetup
                        has_opti_setups = True
                    
                    if has_opti_setups:
                        logger.info("Solving all Optimetrics setups...")
                        oModule.SolveAllSetup("All Optimetrics")
                        solved_via_opti = True
                except Exception as opti_exc:
                    logger.warning(f"Optimetrics solve failed/skipped: {opti_exc}")

                if not solved_via_opti:
                    # Fallback to standard nominal analysis setups
                    if app.setup_names:
                        setup_name = app.setup_names[0]
                        logger.info(f"Solving nominal setup: {setup_name}")
                        app.analyze_setup(setup_name)
                    else:
                        result_errors.append("[solve] No analysis setups found in project to solve.")
                        result_ok = False
            except Exception as exc:
                result_errors.append(f"[solve] analyze failed: {exc}")
                result_ok = False
                
            try:
                app.save_project()
            except Exception:
                pass

        return SolveResult(
            ok=result_ok,
            mode=mode,
            solver="maxwell",
            commands=[{"method": c, "args": {}} for c in result_commands],
            errors=result_errors,
            project_path=project_file,
        )

    def _create_session(
        self, project_file: str, design_name: str, mode: str, errors: list[str],
    ) -> Any:
        """Create Maxwell2d/3d session.

        When new_desktop=False and an active session already has the project
        open, we connect to it without re-opening the file.
        """
        solution = self.solution_type
        try:
            if mode == "2d":
                from ansys.aedt.core import Maxwell2d
                cls = Maxwell2d
            else:
                from ansys.aedt.core import Maxwell3d
                cls = Maxwell3d
                # 3D doesn't use Z/XY suffix
                if solution.endswith(("Z", "z")):
                    solution = solution.rstrip("Zz")

            # When attaching to a running session, try active project first
            if not self.new_desktop:
                proj_name = Path(project_file).stem
                try:
                    # Try by project name (works if already open in AEDT)
                    app = cls(
                        project=proj_name,
                        design=design_name,
                        solution_type=solution,
                        non_graphical=self.non_graphical,
                        new_desktop=False,
                    )
                except Exception:
                    try:
                        # Try with full path (project not yet open)
                        app = cls(
                            project=project_file,
                            design=design_name,
                            solution_type=solution,
                            non_graphical=self.non_graphical,
                            new_desktop=False,
                            remove_lock=True,
                        )
                    except Exception:
                        # Last resort: connect to whatever is active
                        app = cls(
                            solution_type=solution,
                            non_graphical=self.non_graphical,
                            new_desktop=False,
                        )
            else:
                app = cls(
                    project=project_file,
                    design=design_name,
                    solution_type=solution,
                    non_graphical=self.non_graphical,
                    new_desktop=True,
                    remove_lock=True,
                )

            app.modeler.model_units = "mm"
            return app
        except (ImportError, ModuleNotFoundError):
            errors.append("[session] PyAEDT not available")
            return None
        except Exception as exc:
            errors.append(f"[session] Maxwell init failed: {exc}")
            return None
