"""Rewrite tutorial notebook in pyaedt style with apply_dosa_to_maxwell."""
import json
from pathlib import Path

NB_PATH = Path(__file__).parents[1] / "tutorial_dosa_maxwell_mvp.ipynb"

def cell_md(id_, *lines):
    return {"cell_type": "markdown", "id": id_, "metadata": {}, "source": list(lines)}

def cell_code(id_, *lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": id_,
        "metadata": {},
        "outputs": [],
        "source": list(lines),
    }

nb = {
    "cells": [
        cell_md("intro-md",
            "# DoSA-Maxwell 통합 자동화 튜토리얼\n",
            "\n",
            "DoSA 설계 파일을 파싱한 후 **`apply_dosa_to_maxwell()`** 함수 한 번으로\n",
            "Ansys Maxwell에 형상·재질·여자·설정을 모두 적용합니다.\n",
            "\n",
            "```python\n",
            "parse_dosa_file()        # DoSA .dsa → DesignModel\n",
            "Maxwell2d / Maxwell3d()  # pyaedt 세션 생성 (pyaedt 예제와 동일)\n",
            "apply_dosa_to_maxwell()  # DoSA → Maxwell 변환\n",
            "```\n",
            "\n",
            "> **AEDT 버전:** 2026.1 · **모드:** non-graphical · **단위:** mm\n",
        ),

        cell_code("imports",
            "from pathlib import Path\n",
            "import sys\n",
            "\n",
            "# ── 경로 설정 ─────────────────────────────────────────────────────────\n",
            'ROOT       = Path(r"E:/KDH/gitDosa_Actuator/DoSA-2D/Code/31_DoSA-Maxwell-Automation")\n',
            'SAMPLE_DIR = Path(r"E:/KDH/gitDosa_Actuator/DoSA-2D/Code/11_DoSA-2D/DoSA-2D/Samples")\n',
            'OUTPUT_DIR = ROOT / "output"\n',
            "OUTPUT_DIR.mkdir(exist_ok=True)\n",
            "\n",
            'if str(ROOT / "src") not in sys.path:\n',
            '    sys.path.insert(0, str(ROOT / "src"))\n',
            "\n",
            "# ── pyaedt ────────────────────────────────────────────────────────────\n",
            "import ansys.aedt.core\n",
            "\n",
            "# ── dosa-maxwell: parse + apply 두 함수면 충분 ─────────────────────────\n",
            "from dosa_maxwell import parse_dosa_file, apply_dosa_to_maxwell, get_profile\n",
            "\n",
            'AEDT_VERSION = "2026.1"   # Maxwell 2026 R1\n',
            "NG_MODE      = True        # headless (비그래픽)\n",
            "\n",
            'print(f"ansys.aedt.core : {ansys.aedt.core.__version__}")\n',
            'print(f"AEDT target     : {AEDT_VERSION}")\n',
            'print(f"Output dir      : {OUTPUT_DIR}")\n',
        ),

        cell_md("parse-md", "## 1. DoSA 설계 파싱\n"),

        cell_code("parse-cell",
            'design_sol = parse_dosa_file(SAMPLE_DIR / "Solenoid/Solenoid.dsa")\n',
            'design_vcm = parse_dosa_file(SAMPLE_DIR / "VCM/VCM.dsa")\n',
            "\n",
            "print(f\"Solenoid parts : {[p.name for p in design_sol.parts]}\")\n",
            "print(f\"         tests : {[t.name for t in design_sol.tests]}\")\n",
            "print()\n",
            "print(f\"VCM      parts : {[p.name for p in design_vcm.parts]}\")\n",
            "print(f\"         tests : {[t.name for t in design_vcm.tests]}\")\n",
        ),

        cell_md("sol2d-md",
            "## 2. Solenoid — Maxwell 2D (MagnetostaticXY)\n",
            "\n",
            "pyaedt 예제와 동일하게 세션을 열고,\n",
            "`apply_dosa_to_maxwell()` 한 번으로 DoSA 모델을 적용합니다.\n",
        ),

        cell_code("sol2d-cell",
            'profile = get_profile("le01_2020r1")   # Magnetostatic 프리셋\n',
            "\n",
            "m2d_sol = ansys.aedt.core.Maxwell2d(\n",
            '    project=str(OUTPUT_DIR / "solenoid_2d" / "Solenoid.aedt"),\n',
            '    design="Solenoid_2D",\n',
            '    solution_type="MagnetostaticXY",\n',
            "    version=AEDT_VERSION,\n",
            "    non_graphical=NG_MODE,\n",
            "    new_desktop=True,\n",
            ")\n",
            'm2d_sol.modeler.model_units = "mm"\n',
            "\n",
            "# DoSA → Maxwell: 형상·재질·코일 여자·해석 설정 모두 적용\n",
            "result = apply_dosa_to_maxwell(design_sol, m2d_sol, profile=profile)\n",
            "print(result)\n",
            'for e in result.get("errors", []): print(" !", e)\n',
            "\n",
            "m2d_sol.save_project()\n",
            'print("Saved:", m2d_sol.project_file)\n',
            "m2d_sol.release_desktop(close_projects=False, close_desktop=False)\n",
        ),

        cell_md("vcm2d-md", "## 3. VCM — Maxwell 2D (MagnetostaticXY)\n"),

        cell_code("vcm2d-cell",
            "m2d_vcm = ansys.aedt.core.Maxwell2d(\n",
            '    project=str(OUTPUT_DIR / "vcm_2d" / "VCM.aedt"),\n',
            '    design="VCM_2D",\n',
            '    solution_type="MagnetostaticXY",\n',
            "    version=AEDT_VERSION,\n",
            "    non_graphical=NG_MODE,\n",
            "    new_desktop=False,   # 같은 Desktop 재사용\n",
            ")\n",
            'm2d_vcm.modeler.model_units = "mm"\n',
            "\n",
            "result_vcm = apply_dosa_to_maxwell(design_vcm, m2d_vcm, profile=profile)\n",
            "print(result_vcm)\n",
            'for e in result_vcm.get("errors", []): print(" !", e)\n',
            "\n",
            "m2d_vcm.save_project()\n",
            'print("Saved:", m2d_vcm.project_file)\n',
            "m2d_vcm.release_desktop(close_projects=False, close_desktop=False)\n",
        ),

        cell_md("sol3d-md",
            "## 4. Solenoid — Maxwell 3D (축대칭 → 360° 회전체)\n",
            "\n",
            "DoSA 2D 단면(X=반경, Y=축)을 Y축 기준 360° 회전시켜 3D 솔리드를 생성합니다.\n",
            "`apply_dosa_to_maxwell()`이 Maxwell3d 인스턴스를 받으면 자동으로 3D 처리합니다.\n",
        ),

        cell_code("sol3d-cell",
            "m3d_sol = ansys.aedt.core.Maxwell3d(\n",
            '    project=str(OUTPUT_DIR / "solenoid_3d" / "Solenoid_3D.aedt"),\n',
            '    design="Solenoid_3D",\n',
            '    solution_type="Magnetostatic",\n',
            "    version=AEDT_VERSION,\n",
            "    non_graphical=NG_MODE,\n",
            "    new_desktop=False,\n",
            ")\n",
            'm3d_sol.modeler.model_units = "mm"\n',
            "\n",
            "# Maxwell3d 감지 → polyline 후 sweep_around_axis(Y, 360°) 자동 적용\n",
            "result_3d = apply_dosa_to_maxwell(design_sol, m3d_sol, profile=profile)\n",
            "print(result_3d)\n",
            'for e in result_3d.get("errors", []): print(" !", e)\n',
            "\n",
            "m3d_sol.save_project()\n",
            'print("Saved:", m3d_sol.project_file)\n',
            "m3d_sol.release_desktop(close_projects=False, close_desktop=False)\n",
        ),

        cell_md("vcm3d-md", "## 5. VCM — Maxwell 3D\n"),

        cell_code("vcm3d-cell",
            "m3d_vcm = ansys.aedt.core.Maxwell3d(\n",
            '    project=str(OUTPUT_DIR / "vcm_3d" / "VCM_3D.aedt"),\n',
            '    design="VCM_3D",\n',
            '    solution_type="Magnetostatic",\n',
            "    version=AEDT_VERSION,\n",
            "    non_graphical=NG_MODE,\n",
            "    new_desktop=False,\n",
            ")\n",
            'm3d_vcm.modeler.model_units = "mm"\n',
            "\n",
            "result_vcm3d = apply_dosa_to_maxwell(design_vcm, m3d_vcm, profile=profile)\n",
            "print(result_vcm3d)\n",
            'for e in result_vcm3d.get("errors", []): print(" !", e)\n',
            "\n",
            "m3d_vcm.save_project()\n",
            'print("Saved:", m3d_vcm.project_file)\n',
            "m3d_vcm.release_desktop(close_projects=False, close_desktop=False)\n",
        ),

        cell_md("cleanup-md", "## 6. 세션 정리 및 결과 확인\n"),

        cell_code("cleanup-cell",
            "# 공유 Desktop 세션 완전 종료\n",
            "try:\n",
            "    from ansys.aedt.core import Desktop\n",
            "    Desktop().release_desktop(close_projects=True, close_desktop=True)\n",
            '    print("AEDT desktop released.")\n',
            "except Exception as e:\n",
            '    print(f"Cleanup skipped: {e}")\n',
            "\n",
            'print("\\n=== 생성된 .aedt 파일 ===")\n',
            'for f in sorted(OUTPUT_DIR.rglob("*.aedt")):\n',
            '    print(f"  {f}")\n',
        ),
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "pyMotorEnv_310",
            "language": "python",
            "name": "python3",
        },
        "language_info": {"name": "python", "version": "3.10.11"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

NB_PATH.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")
print(f"Written: {NB_PATH}")
print(f"Cells: {len(nb['cells'])}")
